"""schema iniziale

Revision ID: 80f6da33f0a0
Revises:
Create Date: 2026-05-07 23:29:43.466505

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80f6da33f0a0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partita",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("data_inizio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_fine", sa.DateTime(timezone=True), nullable=True),
        sa.Column("luogo", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("stato_review", sa.String(length=20), nullable=False),
        sa.Column(
            "data_creazione",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "data_aggiornamento",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evento_grezzo",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("partita_id", sa.String(length=36), nullable=False),
        sa.Column("ts_evento", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("fonte", sa.String(length=30), nullable=False),
        sa.Column("confidenza", sa.Float(), nullable=False),
        sa.Column("dati", sa.JSON(), nullable=False),
        sa.Column("validato", sa.Boolean(), nullable=False),
        sa.Column(
            "data_creazione",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["partita_id"], ["partita.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evento_grezzo", schema=None) as batch_op:
        batch_op.create_index(
            "ix_evento_grezzo_partita_ts", ["partita_id", "ts_evento"], unique=False
        )
        batch_op.create_index("ix_evento_grezzo_validato", ["partita_id", "validato"], unique=False)

    op.create_table(
        "giocatore_partita",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("partita_id", sa.String(length=36), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("colore", sa.String(length=20), nullable=False),
        sa.Column("ordine_seduta", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["partita_id"], ["partita.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("giocatore_partita", schema=None) as batch_op:
        batch_op.create_index("ix_giocatore_partita", ["partita_id"], unique=False)

    op.create_table(
        "stato_partita_ricostruito",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("partita_id", sa.String(length=36), nullable=False),
        sa.Column(
            "data_ricostruzione",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("successo", sa.Boolean(), nullable=False),
        sa.Column("n_eventi_totali", sa.Integer(), nullable=False),
        sa.Column("n_eventi_applicati", sa.Integer(), nullable=False),
        sa.Column("stato_serializzato", sa.JSON(), nullable=True),
        sa.Column("errori", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["partita_id"], ["partita.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("partita_id"),
    )
    op.create_table(
        "video",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("partita_id", sa.String(length=36), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("nome_originale", sa.String(length=200), nullable=False),
        sa.Column("ts_inizio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("durata_sec", sa.Float(), nullable=False),
        sa.Column("codec", sa.String(length=20), nullable=True),
        sa.Column("risoluzione", sa.String(length=20), nullable=True),
        sa.Column("dimensione_byte", sa.Integer(), nullable=False),
        sa.Column(
            "data_caricamento",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["partita_id"], ["partita.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("video", schema=None) as batch_op:
        batch_op.create_index("ix_video_partita", ["partita_id"], unique=False)

    op.create_table(
        "evento_validato",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("partita_id", sa.String(length=36), nullable=False),
        sa.Column("ts_evento", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("dati", sa.JSON(), nullable=False),
        sa.Column("evento_grezzo_id", sa.String(length=36), nullable=True),
        sa.Column("validato_da", sa.String(length=100), nullable=False),
        sa.Column(
            "data_creazione",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["evento_grezzo_id"], ["evento_grezzo.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["partita_id"], ["partita.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evento_validato", schema=None) as batch_op:
        batch_op.create_index(
            "ix_evento_validato_partita_ts", ["partita_id", "ts_evento"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evento_validato", schema=None) as batch_op:
        batch_op.drop_index("ix_evento_validato_partita_ts")

    op.drop_table("evento_validato")
    with op.batch_alter_table("video", schema=None) as batch_op:
        batch_op.drop_index("ix_video_partita")

    op.drop_table("video")
    op.drop_table("stato_partita_ricostruito")
    with op.batch_alter_table("giocatore_partita", schema=None) as batch_op:
        batch_op.drop_index("ix_giocatore_partita")

    op.drop_table("giocatore_partita")
    with op.batch_alter_table("evento_grezzo", schema=None) as batch_op:
        batch_op.drop_index("ix_evento_grezzo_validato")
        batch_op.drop_index("ix_evento_grezzo_partita_ts")

    op.drop_table("evento_grezzo")
    op.drop_table("partita")
    # ### end Alembic commands ###
