"""Aggiungi tabelle InferenzaCV e DivergenzaInferita

Revision ID: 9d0e9a878ca9
Revises: 80f6da33f0a0
Create Date: 2026-05-09 12:27:11.051494

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d0e9a878ca9'
down_revision: str | None = '80f6da33f0a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divergenza_inferita',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partita_id', sa.String(length=36), nullable=False),
    sa.Column('evento_validato_id', sa.String(length=36), nullable=True),
    sa.Column('territorio', sa.String(length=50), nullable=False),
    sa.Column('colore', sa.String(length=20), nullable=False),
    sa.Column('valore_motore', sa.Integer(), nullable=False),
    sa.Column('valore_cv', sa.Integer(), nullable=False),
    sa.Column('confidence_cv', sa.Float(), nullable=False),
    sa.Column('delta_assoluto', sa.Integer(), nullable=False),
    sa.Column('inferenze_correlate', sa.JSON(), nullable=False),
    sa.Column('risoluzione', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('creata_il', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('aggiornata_il', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evento_validato_id'], ['evento_validato.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partita_id'], ['partita.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('divergenza_inferita', schema=None) as batch_op:
        batch_op.create_index('ix_divergenza_aperta', ['risoluzione'], unique=False)
        batch_op.create_index('ix_divergenza_evento', ['evento_validato_id'], unique=False)
        batch_op.create_index('ix_divergenza_partita', ['partita_id'], unique=False)

    op.create_table('inferenza_cv',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partita_id', sa.String(length=36), nullable=False),
    sa.Column('evento_validato_id', sa.String(length=36), nullable=True),
    sa.Column('modello_versione', sa.String(length=80), nullable=False),
    sa.Column('territorio', sa.String(length=50), nullable=True),
    sa.Column('colore', sa.String(length=20), nullable=True),
    sa.Column('tipo_pedina_dominante', sa.String(length=30), nullable=True),
    sa.Column('n_armate_stimate', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scomposizione', sa.JSON(), nullable=False),
    sa.Column('creata_il', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('frame_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['evento_validato_id'], ['evento_validato.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partita_id'], ['partita.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inferenza_cv', schema=None) as batch_op:
        batch_op.create_index('ix_inferenza_cv_evento', ['evento_validato_id'], unique=False)
        batch_op.create_index('ix_inferenza_cv_modello', ['modello_versione'], unique=False)
        batch_op.create_index('ix_inferenza_cv_partita', ['partita_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inferenza_cv', schema=None) as batch_op:
        batch_op.drop_index('ix_inferenza_cv_partita')
        batch_op.drop_index('ix_inferenza_cv_modello')
        batch_op.drop_index('ix_inferenza_cv_evento')

    op.drop_table('inferenza_cv')
    with op.batch_alter_table('divergenza_inferita', schema=None) as batch_op:
        batch_op.drop_index('ix_divergenza_partita')
        batch_op.drop_index('ix_divergenza_evento')
        batch_op.drop_index('ix_divergenza_aperta')

    op.drop_table('divergenza_inferita')
    # ### end Alembic commands ###
