"""Schemi Pydantic v2 per validazione I/O degli endpoint API."""

from app.schemi.dati_eventi import (
    DatiArmatePiazzate,
    DatiArmateSpostate,
    DatiAttaccoRisolto,
    DatiCarta,
    DatiObiettivoAssegnato,
    DatiPartitaFine,
    DatiPartitaInizio,
    DatiTerritorioAssegnatoInizio,
    DatiTrisGiocato,
    DatiTurnoFinito,
)
from app.schemi.partita import (
    EventoGrezzoAggiornamento,
    EventoGrezzoBatch,
    EventoGrezzoCreazione,
    EventoGrezzoLettura,
    EventoValidatoAggiornamento,
    EventoValidatoBatch,
    EventoValidatoCreazione,
    EventoValidatoLettura,
    GiocatorePartitaCreazione,
    GiocatorePartitaLettura,
    PartitaAggiornamento,
    PartitaCreazione,
    PartitaLetturaDettaglio,
    PartitaLetturaSommario,
    SetupAutomaticoRichiesta,
    SetupAutomaticoRisposta,
    VideoLettura,
)
from app.schemi.stato_snapshot import (
    ErroreRicostruzioneSchema,
    InfoGiocatoreSchema,
    InfoTerritorioSchema,
    RisultatoRicostruzione,
    StatoPartitaSnapshot,
)

__all__ = [
    "DatiArmatePiazzate",
    "DatiArmateSpostate",
    "DatiAttaccoRisolto",
    "DatiCarta",
    "DatiObiettivoAssegnato",
    "DatiPartitaFine",
    "DatiPartitaInizio",
    "DatiTerritorioAssegnatoInizio",
    "DatiTrisGiocato",
    "DatiTurnoFinito",
    "ErroreRicostruzioneSchema",
    "EventoGrezzoAggiornamento",
    "EventoGrezzoBatch",
    "EventoGrezzoCreazione",
    "EventoGrezzoLettura",
    "EventoValidatoAggiornamento",
    "EventoValidatoBatch",
    "EventoValidatoCreazione",
    "EventoValidatoLettura",
    "GiocatorePartitaCreazione",
    "GiocatorePartitaLettura",
    "InfoGiocatoreSchema",
    "InfoTerritorioSchema",
    "PartitaAggiornamento",
    "PartitaCreazione",
    "PartitaLetturaDettaglio",
    "PartitaLetturaSommario",
    "RisultatoRicostruzione",
    "SetupAutomaticoRichiesta",
    "SetupAutomaticoRisposta",
    "StatoPartitaSnapshot",
    "VideoLettura",
]
