"""
Motore di gioco Risiko classico Editrice Giochi.

Pacchetto Python puro che implementa le regole del Risiko italiano in modo
indipendente da UI, database, hardware. Tutto è testabile con pytest.
"""

from risiko_engine.bonus import (
    BONUS_CARTA_SU_PROPRIO_TERRITORIO,
    BONUS_TERRITORI_MIN,
    BONUS_TRIS_CANNONI,
    BONUS_TRIS_CAVALIERI,
    BONUS_TRIS_FANTI,
    BONUS_TRIS_MISTO,
    bonus_carte_su_territori,
    bonus_combinazione,
    bonus_per_continenti,
    bonus_per_territori,
    calcola_rinforzi_totali,
    continenti_controllati,
    is_tris_valido,
)
from risiko_engine.carte import (
    MAZZO_INIZIALE,
    Carta,
    Simbolo,
    carta_per_territorio,
    nuovo_mazzo_mescolato,
)
from risiko_engine.combattimento import (
    MAX_DADI,
    RisultatoCombattimento,
    lancia_dadi,
    max_dadi_attaccante,
    max_dadi_difensore,
    risolvi_combattimento,
)
from risiko_engine.gestore_mazzo import (
    GestoreMazzo,
    MazzoEsauritoError,
)
from risiko_engine.mappa import (
    ADIACENZE,
    BONUS_CONTINENTE,
    TERRITORI,
    Continente,
    adiacenti_a,
    bonus_continente,
    continente_di,
    territori_di,
)
from risiko_engine.obiettivi import (
    OBIETTIVI,
    Obiettivo,
    conta_obiettivi,
    obiettivo_per_id,
    obiettivo_per_nome,
    verifica_vittoria,
)
from risiko_engine.state_machine import (
    ArmateNonTuttePiazzateError,
    AzioneIllegaleError,
    FaseSbagliataError,
    FaseTurno,
    MotorePartita,
    SetupIncompletoError,
    SpostamentoGiaEffettuatoError,
    TrisGiaGiocatoError,
    TrisInvalidoError,
)
from risiko_engine.stato_partita import (
    ArmateInsufficientiError,
    CarteInsufficientiError,
    ColoreDuplicatoError,
    ColoreGiocatore,
    ConfigurazioneGiocatore,
    GiocatoreEliminatoError,
    GiocatoreInesistenteError,
    InfoGiocatoreCompleta,
    InfoGiocatorePubblica,
    InfoTerritorio,
    NumeroGiocatoriError,
    PlayerIdDuplicatoError,
    StatoPartita,
    StatoPartitaError,
    TerritorioInesistenteError,
    TerritorioNonAssegnatoError,
    VistaArbitro,
    VistaGiocatore,
    VistaPostPartita,
    VistaPubblica,
)

__version__ = "1.0.0"

__all__ = [
    "ADIACENZE",
    "BONUS_CARTA_SU_PROPRIO_TERRITORIO",
    "BONUS_CONTINENTE",
    "BONUS_TERRITORI_MIN",
    "BONUS_TRIS_CANNONI",
    "BONUS_TRIS_CAVALIERI",
    "BONUS_TRIS_FANTI",
    "BONUS_TRIS_MISTO",
    "MAX_DADI",
    "MAZZO_INIZIALE",
    "OBIETTIVI",
    "TERRITORI",
    "ArmateInsufficientiError",
    "ArmateNonTuttePiazzateError",
    "AzioneIllegaleError",
    "Carta",
    "CarteInsufficientiError",
    "ColoreDuplicatoError",
    "ColoreGiocatore",
    "ConfigurazioneGiocatore",
    "Continente",
    "FaseSbagliataError",
    "FaseTurno",
    "GestoreMazzo",
    "GiocatoreEliminatoError",
    "GiocatoreInesistenteError",
    "InfoGiocatoreCompleta",
    "InfoGiocatorePubblica",
    "InfoTerritorio",
    "MazzoEsauritoError",
    "MotorePartita",
    "NumeroGiocatoriError",
    "Obiettivo",
    "PlayerIdDuplicatoError",
    "RisultatoCombattimento",
    "SetupIncompletoError",
    "Simbolo",
    "SpostamentoGiaEffettuatoError",
    "StatoPartita",
    "StatoPartitaError",
    "TerritorioInesistenteError",
    "TerritorioNonAssegnatoError",
    "TrisGiaGiocatoError",
    "TrisInvalidoError",
    "VistaArbitro",
    "VistaGiocatore",
    "VistaPostPartita",
    "VistaPubblica",
    "adiacenti_a",
    "bonus_carte_su_territori",
    "bonus_combinazione",
    "bonus_continente",
    "bonus_per_continenti",
    "bonus_per_territori",
    "calcola_rinforzi_totali",
    "carta_per_territorio",
    "conta_obiettivi",
    "continente_di",
    "continenti_controllati",
    "is_tris_valido",
    "lancia_dadi",
    "max_dadi_attaccante",
    "max_dadi_difensore",
    "nuovo_mazzo_mescolato",
    "obiettivo_per_id",
    "obiettivo_per_nome",
    "risolvi_combattimento",
    "territori_di",
    "verifica_vittoria",
]
